networks:
  neo4j-internal:

services:
  # webapp:
  #   image: webapp
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db
  db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"
